### ISSUE TITLE
o1js is not compatible with AWS Graviton2 (Neoverse-N1 cores) ARM processor

### ISSUE THREAD

**Issue by dfstio** [o1-labs/o1js#1525]
When compiling (without existing cache) or proving on AWS Graviton2 ARM processor, o1js hangs out. 
All other o1js code works as intended. Compilation also works if the prover keys have already been cached.

Graviton2 processors can be used on AWS lambda instances by setting arm64 architecture in the serverless.yml
```
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  architecture: arm64
```
They are 20% cheaper than x86 and probably faster.
